/*
 * TestFrame.java
 *
 * Created on May 10, 2006, 3:40 PM
 */

package magnifyglass;

import java.awt.Color;
import java.awt.Graphics2D;
import javax.swing.JComponent;
import org.jdesktop.swingx.painter.MattePainter;
import org.jdesktop.swingx.painter.Painter;


/**
 *
 * @author  jm158417
 */
public class TestFrame extends javax.swing.JFrame {
    
    /** Creates new form TestFrame */
    public TestFrame() {
        initComponents();
    }
    
    public Main main;
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        subpanel = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        valfield2 = new javax.swing.JTextField();
        overlayed = new javax.swing.JButton();
        validatedTextfield = new javax.swing.JTextField();
        validateButton = new javax.swing.JToggleButton();
        posSlider = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jRadioButton2.setText("jRadioButton2");
        jRadioButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jRadioButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBox1.setText("jCheckBox1");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBox2.setText("jCheckBox2");
        jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBox3.setText("jCheckBox3");
        jCheckBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));

        valfield2.setText("jTextField2");

        overlayed.setText("Overlayed");

        validatedTextfield.setText("jTextField3");

        validateButton.setText("Validate!");
        validateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validateButtonActionPerformed(evt);
            }
        });

        posSlider.setMaximum(200);
        posSlider.setValue(0);
        posSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                posSliderStateChanged(evt);
            }
        });

        org.jdesktop.layout.GroupLayout subpanelLayout = new org.jdesktop.layout.GroupLayout(subpanel);
        subpanel.setLayout(subpanelLayout);
        subpanelLayout.setHorizontalGroup(
            subpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(subpanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(subpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(subpanelLayout.createSequentialGroup()
                        .add(subpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jCheckBox1)
                            .add(jCheckBox2))
                        .add(29, 29, 29)
                        .add(subpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(validatedTextfield)
                            .add(valfield2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)))
                    .add(jCheckBox3))
                .add(6, 6, 6)
                .add(subpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(validateButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(overlayed, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
            .add(posSlider, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
        );
        subpanelLayout.setVerticalGroup(
            subpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(subpanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(subpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCheckBox1)
                    .add(valfield2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(overlayed))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(subpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(subpanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(validatedTextfield, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(validateButton))
                    .add(subpanelLayout.createSequentialGroup()
                        .add(jCheckBox2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCheckBox3)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 38, Short.MAX_VALUE)
                .add(posSlider, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(subpanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1))
                    .add(jRadioButton1)
                    .add(jRadioButton2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jLabel1)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(19, 19, 19)
                .add(jRadioButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jRadioButton2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(subpanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void posSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_posSliderStateChanged

        main.magGlassOverlay.setMagLocation(posSlider.getValue());
// TODO add your handling code here:
    }//GEN-LAST:event_posSliderStateChanged

    private void validateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validateButtonActionPerformed
        if(validateButton.isSelected()) {
            main.validationOverlay.addTarget(validatedTextfield);
            main.validationOverlay.addTarget(valfield2);
//            main.validationOverlay.setPainter(new Painter() {
//                public void paint(Graphics2D g, JComponent component) {
//                    g.setColor(new Color(255,0,0,50));
//                    g.fillRect(0,0,component.getWidth(),component.getHeight());
//                    g.setColor(Color.red);
//                    g.fillOval(-4,-4,4*2,4*2);
//                    g.setColor(Color.black);
//                    g.drawOval(-4,-4,8,8);
//                    g.drawLine(-4,-4,4,4);
//                    g.drawLine(4,-4,-4,4);
//                }
//            });
        } else {
            main.validationOverlay.removeTarget(validatedTextfield);
            main.validationOverlay.removeTarget(valfield2);
        }        
    }//GEN-LAST:event_validateButtonActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JButton overlayed;
    private javax.swing.JSlider posSlider;
    public javax.swing.JPanel subpanel;
    private javax.swing.JTextField valfield2;
    public javax.swing.JToggleButton validateButton;
    public javax.swing.JTextField validatedTextfield;
    // End of variables declaration//GEN-END:variables
    
}
