/*
 */

/*
 * Main.java
 *
 * Created on 25.05.2011, 07:32:47
 */
package bubblepanel;

import java.lang.management.ManagementFactory;
import java.lang.management.OperatingSystemMXBean;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;



/**
 *
 * @author Gerrit Grunwald <han.solo at muenster.de>
 */
public class Main extends javax.swing.JFrame
{
    /** Creates new form Main */
    public Main()
    {
    	Thread t = new Thread(new Runnable() {
    		public void run() {
    			while (true) {
    				System.out.println("load="+ManagementFactory.getOperatingSystemMXBean().getSystemLoadAverage());
    				printUsage();
    				try {
						Thread.currentThread().sleep(10000);
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
    			}
    		}
    	});
    	t.start();
    	
    	System.out.println("processors="+ Runtime.getRuntime().availableProcessors());
        initComponents();          
    }
    
    private static void printUsage() {
    	  OperatingSystemMXBean operatingSystemMXBean = ManagementFactory.getOperatingSystemMXBean();
    	  for (Method method : operatingSystemMXBean.getClass().getDeclaredMethods()) {
    	    method.setAccessible(true);
    	    if (method.getName().startsWith("get") ) {
    	            Object value;
    	        try {
    	            value = method.invoke(operatingSystemMXBean);
    	        } catch (Exception e) {
    	            value = e;
    	        } // try
    	        System.out.println(method.getName() + " = " + value);
    	    } // if
    	  } // for
    	}


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bubblePanel1 = new BubblePanel();
        labelHeader = new javax.swing.JLabel();
        buttonValidate = new javax.swing.JToggleButton();
        labelFirstName = new javax.swing.JLabel();
        labelLastName = new javax.swing.JLabel();
        textFieldFirstName = new javax.swing.JTextField();
        textFieldLastName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fun validation panel");

        bubblePanel1.setBackground(new java.awt.Color(0, 0, 51));

        labelHeader.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        labelHeader.setForeground(new java.awt.Color(255, 102, 0));
        labelHeader.setText("Validation with fun...");

        buttonValidate.setText("Validate");
        buttonValidate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionHandler(evt);
            }
        });

        labelFirstName.setForeground(new java.awt.Color(255, 255, 255));
        labelFirstName.setText("First name");

        labelLastName.setForeground(new java.awt.Color(255, 255, 255));
        labelLastName.setText("Last name");

        textFieldFirstName.setBackground(new java.awt.Color(0,0,0,0));
        textFieldFirstName.setForeground(new java.awt.Color(255, 153, 51));

        textFieldLastName.setBackground(new java.awt.Color(0,0,0,0));
        textFieldLastName.setForeground(new java.awt.Color(255, 153, 51));

        org.jdesktop.layout.GroupLayout bubblePanel1Layout = new org.jdesktop.layout.GroupLayout(bubblePanel1);
        bubblePanel1.setLayout(bubblePanel1Layout);
        bubblePanel1Layout.setHorizontalGroup(
            bubblePanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bubblePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(bubblePanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelHeader)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, buttonValidate)
                    .add(bubblePanel1Layout.createSequentialGroup()
                        .add(bubblePanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelFirstName)
                            .add(labelLastName))
                        .add(18, 18, 18)
                        .add(bubblePanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(textFieldLastName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .add(textFieldFirstName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))))
                .addContainerGap())
        );
        bubblePanel1Layout.setVerticalGroup(
            bubblePanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bubblePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(labelHeader)
                .add(33, 33, 33)
                .add(bubblePanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelFirstName)
                    .add(textFieldFirstName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(bubblePanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labelLastName)
                    .add(textFieldLastName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 60, Short.MAX_VALUE)
                .add(buttonValidate)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bubblePanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bubblePanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void actionHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionHandler
    if (evt.getSource().equals(buttonValidate))
    {
        if (buttonValidate.isSelected())
        {
            buttonValidate.setText("invalidate");
        }
        else
        {
            buttonValidate.setText("validate");
        }
        bubblePanel1.setValidated(buttonValidate.isSelected());
    }
}//GEN-LAST:event_actionHandler

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                final Main APP = new Main();
                APP.setLocationRelativeTo(null);
                APP.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BubblePanel bubblePanel1;
    private javax.swing.JToggleButton buttonValidate;
    private javax.swing.JLabel labelFirstName;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelLastName;
    private javax.swing.JTextField textFieldFirstName;
    private javax.swing.JTextField textFieldLastName;
    // End of variables declaration//GEN-END:variables
}
