package flipchar;


/**
 *
 * @author Gerrit Grunwald <han.solo at muenster.de>
 */
public class Demo extends javax.swing.JFrame implements java.awt.event.ActionListener {

    private final java.util.Random RND = new java.util.Random();
    private final javax.swing.Timer TIMER = new javax.swing.Timer(12000, this);
    private boolean toggle = true;
    
    /** Creates new form Demo */
    public Demo() {
        initComponents();        
        GlobalTimer.INSTANCE.startTimer();        
        TIMER.start();        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flipCharPanel1 = new FlipCharPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FlipChar component demo");
        setResizable(false);

        flipCharPanel1.setFontColor(new java.awt.Color(255, 255, 204));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(flipCharPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(flipCharPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(final java.awt.event.ActionEvent EVENT) {
        final java.awt.Color FONT_COLOR = new java.awt.Color(RND.nextInt(255), RND.nextInt(255), RND.nextInt(255));
        flipCharPanel1.setFontColor(FONT_COLOR);        
        if (toggle) {
            flipCharPanel1.setText("Swing is fun...");
            toggle = false;
        } else {
            flipCharPanel1.setText("Enjoy Java Swing");
            toggle = true;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                final Demo APP = new Demo();
                APP.setLocationRelativeTo(null);
                APP.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private FlipCharPanel flipCharPanel1;
    // End of variables declaration//GEN-END:variables
}
