package flipchar;

/**
 *
 * @author Gerrit Grunwald <han.solo at muenster.de>
 */
public class FlipCharPanel extends javax.swing.JPanel {
    // <editor-fold defaultstate="collapsed" desc="Variable declarations">
    private String text = "          ";
    private FlipChar[] flipCharArray = new FlipChar[16];
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Constructor">
    public FlipCharPanel() {
        initComponents();
        init();
    }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="Initialization">
    private void init() {
        flipCharArray[0] = flipChar1;
        flipCharArray[1] = flipChar2;
        flipCharArray[2] = flipChar3;
        flipCharArray[3] = flipChar4;
        flipCharArray[4] = flipChar5;
        flipCharArray[5] = flipChar6;
        flipCharArray[6] = flipChar7;
        flipCharArray[7] = flipChar8;
        flipCharArray[8] = flipChar9;
        flipCharArray[9] = flipChar10;
        flipCharArray[10] = flipChar11;
        flipCharArray[11] = flipChar12;
        flipCharArray[12] = flipChar13;
        flipCharArray[13] = flipChar14;
        flipCharArray[14] = flipChar15;
        flipCharArray[15] = flipChar16;
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Getter and Setter">
    public String getText() {
        return this.text;
    }

    public void setText(String text) {
        this.text = text;
        flipIt();
    }
    
    public java.awt.Color getFontColor() {
        return flipChar1.getFontColor();
    }
    
    public void setFontColor(final java.awt.Color FONT_COLOR) {
        for (FlipChar flipChar : flipCharArray) {
            flipChar.setFontColor(FONT_COLOR);
        }        
    }
    // </editor-fold>
    
    // <editor-fold defaultstate="collapsed" desc="Misc">
    public void clearPanel() {
        setText("          ");
    }

    private void flipIt() {
        for (int i = 0; i < 16; i++) {
            if (i >= text.length()) {
                flipCharArray[i].setCharacter(" ");
            } else {
                flipCharArray[i].setCharacter(this.text.toUpperCase().substring(i, i + 1));
            }
        }
    }
    // </editor-fold>
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel1 = new BackgroundPanel();
        flipChar15 = new FlipChar();
        flipChar16 = new FlipChar();
        flipChar13 = new FlipChar();
        flipChar14 = new FlipChar();
        flipChar11 = new FlipChar();
        flipChar12 = new FlipChar();
        flipChar9 = new FlipChar();
        flipChar10 = new FlipChar();
        flipChar1 = new FlipChar();
        flipChar8 = new FlipChar();
        flipChar5 = new FlipChar();
        flipChar4 = new FlipChar();
        flipChar3 = new FlipChar();
        flipChar2 = new FlipChar();
        flipChar7 = new FlipChar();
        flipChar6 = new FlipChar();

        org.jdesktop.layout.GroupLayout flipChar15Layout = new org.jdesktop.layout.GroupLayout(flipChar15);
        flipChar15.setLayout(flipChar15Layout);
        flipChar15Layout.setHorizontalGroup(
            flipChar15Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 45, Short.MAX_VALUE)
        );
        flipChar15Layout.setVerticalGroup(
            flipChar15Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 62, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout flipChar16Layout = new org.jdesktop.layout.GroupLayout(flipChar16);
        flipChar16.setLayout(flipChar16Layout);
        flipChar16Layout.setHorizontalGroup(
            flipChar16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 45, Short.MAX_VALUE)
        );
        flipChar16Layout.setVerticalGroup(
            flipChar16Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 62, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout flipChar13Layout = new org.jdesktop.layout.GroupLayout(flipChar13);
        flipChar13.setLayout(flipChar13Layout);
        flipChar13Layout.setHorizontalGroup(
            flipChar13Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 45, Short.MAX_VALUE)
        );
        flipChar13Layout.setVerticalGroup(
            flipChar13Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 62, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout flipChar14Layout = new org.jdesktop.layout.GroupLayout(flipChar14);
        flipChar14.setLayout(flipChar14Layout);
        flipChar14Layout.setHorizontalGroup(
            flipChar14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 45, Short.MAX_VALUE)
        );
        flipChar14Layout.setVerticalGroup(
            flipChar14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 62, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout flipChar11Layout = new org.jdesktop.layout.GroupLayout(flipChar11);
        flipChar11.setLayout(flipChar11Layout);
        flipChar11Layout.setHorizontalGroup(
            flipChar11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 45, Short.MAX_VALUE)
        );
        flipChar11Layout.setVerticalGroup(
            flipChar11Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 62, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout flipChar12Layout = new org.jdesktop.layout.GroupLayout(flipChar12);
        flipChar12.setLayout(flipChar12Layout);
        flipChar12Layout.setHorizontalGroup(
            flipChar12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 45, Short.MAX_VALUE)
        );
        flipChar12Layout.setVerticalGroup(
            flipChar12Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 62, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout flipChar9Layout = new org.jdesktop.layout.GroupLayout(flipChar9);
        flipChar9.setLayout(flipChar9Layout);
        flipChar9Layout.setHorizontalGroup(
            flipChar9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 45, Short.MAX_VALUE)
        );
        flipChar9Layout.setVerticalGroup(
            flipChar9Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 62, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout flipChar10Layout = new org.jdesktop.layout.GroupLayout(flipChar10);
        flipChar10.setLayout(flipChar10Layout);
        flipChar10Layout.setHorizontalGroup(
            flipChar10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 45, Short.MAX_VALUE)
        );
        flipChar10Layout.setVerticalGroup(
            flipChar10Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 62, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout flipChar1Layout = new org.jdesktop.layout.GroupLayout(flipChar1);
        flipChar1.setLayout(flipChar1Layout);
        flipChar1Layout.setHorizontalGroup(
            flipChar1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 45, Short.MAX_VALUE)
        );
        flipChar1Layout.setVerticalGroup(
            flipChar1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 62, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout flipChar8Layout = new org.jdesktop.layout.GroupLayout(flipChar8);
        flipChar8.setLayout(flipChar8Layout);
        flipChar8Layout.setHorizontalGroup(
            flipChar8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 45, Short.MAX_VALUE)
        );
        flipChar8Layout.setVerticalGroup(
            flipChar8Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 62, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout flipChar5Layout = new org.jdesktop.layout.GroupLayout(flipChar5);
        flipChar5.setLayout(flipChar5Layout);
        flipChar5Layout.setHorizontalGroup(
            flipChar5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 45, Short.MAX_VALUE)
        );
        flipChar5Layout.setVerticalGroup(
            flipChar5Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 62, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout flipChar4Layout = new org.jdesktop.layout.GroupLayout(flipChar4);
        flipChar4.setLayout(flipChar4Layout);
        flipChar4Layout.setHorizontalGroup(
            flipChar4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 45, Short.MAX_VALUE)
        );
        flipChar4Layout.setVerticalGroup(
            flipChar4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 62, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout flipChar3Layout = new org.jdesktop.layout.GroupLayout(flipChar3);
        flipChar3.setLayout(flipChar3Layout);
        flipChar3Layout.setHorizontalGroup(
            flipChar3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 45, Short.MAX_VALUE)
        );
        flipChar3Layout.setVerticalGroup(
            flipChar3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 62, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout flipChar2Layout = new org.jdesktop.layout.GroupLayout(flipChar2);
        flipChar2.setLayout(flipChar2Layout);
        flipChar2Layout.setHorizontalGroup(
            flipChar2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 45, Short.MAX_VALUE)
        );
        flipChar2Layout.setVerticalGroup(
            flipChar2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 62, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout flipChar7Layout = new org.jdesktop.layout.GroupLayout(flipChar7);
        flipChar7.setLayout(flipChar7Layout);
        flipChar7Layout.setHorizontalGroup(
            flipChar7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 45, Short.MAX_VALUE)
        );
        flipChar7Layout.setVerticalGroup(
            flipChar7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 62, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout flipChar6Layout = new org.jdesktop.layout.GroupLayout(flipChar6);
        flipChar6.setLayout(flipChar6Layout);
        flipChar6Layout.setHorizontalGroup(
            flipChar6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 45, Short.MAX_VALUE)
        );
        flipChar6Layout.setVerticalGroup(
            flipChar6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 62, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout backgroundPanel1Layout = new org.jdesktop.layout.GroupLayout(backgroundPanel1);
        backgroundPanel1.setLayout(backgroundPanel1Layout);
        backgroundPanel1Layout.setHorizontalGroup(
            backgroundPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(backgroundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(flipChar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(flipChar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(flipChar3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(flipChar4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(flipChar5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(flipChar6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(flipChar7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(flipChar8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(flipChar9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(flipChar10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(flipChar11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(flipChar12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(flipChar13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(flipChar14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(flipChar15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, 0)
                .add(flipChar16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        backgroundPanel1Layout.setVerticalGroup(
            backgroundPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(backgroundPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(backgroundPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(flipChar16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(flipChar15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(flipChar14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(flipChar13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(flipChar12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(flipChar11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(flipChar10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(flipChar9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(flipChar8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(flipChar7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(flipChar6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(flipChar5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(flipChar4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(flipChar3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(flipChar2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(flipChar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(backgroundPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(backgroundPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BackgroundPanel backgroundPanel1;
    private FlipChar flipChar1;
    private FlipChar flipChar10;
    private FlipChar flipChar11;
    private FlipChar flipChar12;
    private FlipChar flipChar13;
    private FlipChar flipChar14;
    private FlipChar flipChar15;
    private FlipChar flipChar16;
    private FlipChar flipChar2;
    private FlipChar flipChar3;
    private FlipChar flipChar4;
    private FlipChar flipChar5;
    private FlipChar flipChar6;
    private FlipChar flipChar7;
    private FlipChar flipChar8;
    private FlipChar flipChar9;
    // End of variables declaration//GEN-END:variables
}
